[book]
authors = ["rsapkf"]
language = "en"
multilingual = false
src = "src"
title = "[rsapkf/42]"

[build]
create-missing = false

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/rsapkf/42"
git-repository-icon = "fa-github"
additional-css = ["theme/custom.css"]
